baseURL = 'http://kablogs.fun/'
languageCode = 'en-us'
title = 'Kablogs'
theme = "hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/kalogs-c"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/carloshcamilo/"
