baseURL = 'https://kalogs-c.github.io/kablogs'
languageCode = 'en-us'
title = 'Kablogs'
theme = "hugo-blog-awesome"

enableEmoji = true

[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    pageRef = "posts"
    name = "Posts"
    url = "/posts/"
    weigth = 20
  [[menu.main]]
    pageRef = "about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Kablogs"
  defaultColor = "auto"
  description = "Developing apps"

[params.author]
  intro = "Carlos Camilo"
  name = "Carlos Camilo"
  description = "Sharing some stuffs that I've learn 🇧🇷"

[[params.socialIcons]]
name = "github"
url = "https://github.com/kalogs-c"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/carloshcamilo/"
